### ISSUE TITLE
Time is one hour off

### ISSUE THREAD

**Issue by TheLion** [naruhaxor/AndroidKlipperScreen#5]
Just noticed that the time displayed on the KlipperScreen running on my Android tablet, is one hour off from the one displayed in Android. 

The time on the RPi running Klipper and KlipperScreen is also set correctly. 

Where is the time displayed, getting the settings from?

**Comment by naruhaxor** [comment]
I actually do not know the answer to that question. That's probably
entirely within the clipper screen code.

**Comment by TheLion** [comment]
> I actually do not know the answer to that question. That's probably entirely within the clipper screen code.
> […](#)

Of course, you are right. Your project doesn't have anything to do with the code of KlipperScreen ;-)

I'll create an issue there.
